Changed stackimage call to include processAllImages parameter to add …
jwu910/photo-booth-automation pull request #8
Opened 2017-07-30 04:00 UTC by jwu910

…all files in workflow to the print folder or not

2017-07-30 05:55 UTC, rainrivas requested changes

2017-07-30 05:55 UTC, rainrivas commented on stackImage.py
> +	stackImage takes two arguments, args[0] is the base image and args[1] is the image to superimpose over the base.
This no longer looks accurate @jwu910 , from what I'm reading you now take 3 arguments and args[2] is a flag of sorts

2017-07-31 02:26 UTC, jwu910 commented on stackImage.py
> +	stackImage takes two arguments, args[0] is the base image and args[1] is the image to superimpose over the base.
Oh you're right. The docstring didn't get updated. Thanks

2017-07-31 18:01 UTC, rainrivas approved these changes

2017-07-31 18:48 UTC, merged